version: 3

tasks:
  default:
    cmd: task -l
    silent: true

  setup: &setup
    desc: Set up RELATE
    env:
      COMPOSE_PROJECT_NAME: relate-{{.DISTRIBUTION}}
      DISTRIBUTION: "{{.DISTRIBUTION}}"
    cmds:
      - cmd: docker compose run --rm app uv run python manage.py migrate
      - cmd: docker compose run --rm app uv run python manage.py createsuperuser --noinput
      - cmd: docker compose run --rm app ./collectstatic.sh
    requires:
      vars:
        - name: DISTRIBUTION
          enum:
            - alpine
            - debian

  start:
    <<: *setup
    desc: Start RELATE
    cmds:
      - cmd: docker compose up -d {{.CLI_ARGS}}

  stop:
    <<: *setup
    desc: Stop RELATE
    cmds:
      - cmd: docker compose down {{.CLI_ARGS}}

  logs:
    <<: *setup
    desc: Display Docker Compose logs
    cmds:
      - cmd: docker compose logs -f {{.CLI_ARGS}}
