version: 3

tasks:
  default:
    cmd: task -a
    silent: true

  setup-alpine:
    cmd:
      task: setup
      vars:
        COMPOSE_FILES: -f compose.yml -f compose.alpine.yml
        COMPOSE_PROJECT_NAME: relate-alpine

  run-alpine:
    cmd:
      task: run
      vars:
        COMPOSE_FILES: -f compose.yml -f compose.alpine.yml
        COMPOSE_PROJECT_NAME: relate-alpine

  shutdown-alpine:
    cmd:
      task: shutdown
      vars:
        COMPOSE_FILES: -f compose.yml -f compose.alpine.yml
        COMPOSE_PROJECT_NAME: relate-alpine

  logs-alpine:
    cmd:
      task: logs
      vars:
        COMPOSE_FILES: -f compose.yml -f compose.alpine.yml
        COMPOSE_PROJECT_NAME: relate-alpine

  setup-debian:
    cmd:
      task: setup
      vars:
        COMPOSE_FILES: -f compose.yml -f compose.debian.yml
        COMPOSE_PROJECT_NAME: relate-debian

  run-debian:
    cmd:
      task: run
      vars:
        COMPOSE_FILES: -f compose.yml -f compose.debian.yml
        COMPOSE_PROJECT_NAME: relate-debian

  shutdown-debian:
    cmd:
      task: shutdown
      vars:
        COMPOSE_FILES: -f compose.yml -f compose.debian.yml
        COMPOSE_PROJECT_NAME: relate-debian

  logs-debian:
    cmd:
      task: logs
      vars:
        COMPOSE_FILES: -f compose.yml -f compose.debian.yml
        COMPOSE_PROJECT_NAME: relate-debian

  setup:
    cmd: docker compose {{.COMPOSE_FILES}} -p {{.COMPOSE_PROJECT_NAME}} run --rm app sh -c "python manage.py migrate && python manage.py createsuperuser --noinput"
    internal: true

  run:
    cmd: docker compose {{.COMPOSE_FILES}} -p {{.COMPOSE_PROJECT_NAME}} up -d {{.CLI_ARGS}}
    internal: true

  shutdown:
    cmd: docker compose {{.COMPOSE_FILES}} -p {{.COMPOSE_PROJECT_NAME}} down {{.CLI_ARGS}}
    internal: true

  logs:
    cmd: docker compose {{.COMPOSE_FILES}} -p {{.COMPOSE_PROJECT_NAME}} logs -f {{.CLI_ARGS}}
    internal: true
