version: 3

tasks:
  default:
    cmd: task -a
    silent: true

  setup: &setup
    env:
      COMPOSE_PROJECT_NAME: relate-{{.DISTRIBUTION}}
      DISTRIBUTION: "{{.DISTRIBUTION}}"
    cmd: docker compose run --rm app sh -c "python manage.py migrate && python manage.py createsuperuser --noinput"
    requires:
      vars:
        - name: DISTRIBUTION
          enum:
            - alpine
            - debian

  run:
    <<: *setup
    cmd: docker compose up -d {{.CLI_ARGS}}

  shutdown:
    <<: *setup
    cmd: docker compose down {{.CLI_ARGS}}

  logs:
    <<: *setup
    cmd: docker compose logs -f {{.CLI_ARGS}}
