version: 3

tasks:
  default:
    cmd: task -l
    silent: true

  setup: &setup
    desc: Set up RELATE
    env:
      COMPOSE_PROJECT_NAME: relate-{{.DISTRIBUTION}}
      DISTRIBUTION: "{{.DISTRIBUTION}}"
    cmd: docker compose run --rm app sh -c "python manage.py migrate && python manage.py createsuperuser --noinput"
    requires:
      vars:
        - name: DISTRIBUTION
          enum:
            - alpine
            - debian

  start:
    <<: *setup
    desc: Start RELATE
    cmd: docker compose up -d {{.CLI_ARGS}}

  stop:
    <<: *setup
    desc: Stop RELATE
    cmd: docker compose down {{.CLI_ARGS}}

  logs:
    <<: *setup
    desc: Display Docker Compose logs
    cmd: docker compose logs -f {{.CLI_ARGS}}
