name: Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        os:
          - alpine
          - debian
        python-version:
          - "3.10"
          - "3.11"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-${{ matrix.os }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/relate:python${{ matrix.python-version }}-${{ matrix.os }}
          push: true
